defaults:
- _self_
- launcher: local
- data: pusht
- model: lewm
- override hydra/job_logging: disabled
- override hydra/hydra_logging: disabled
embed_dim: 192
history_size: 63
img_size: 224
loader:
  batch_size: 8
  num_workers: ${num_workers}
  persistent_workers: true
  pin_memory: true
  prefetch_factor: 3
loss:
  sigreg:
    kwargs:
      knots: 17
      num_proj: 1024
    weight: 0.09
num_preds: 1
num_workers: 4
optimizer:
  lr: 1e-4
  type: AdamW
  weight_decay: 1e-3
output_model_name: lewm
checkpoint_run_name: ${data.task_name}
seed: 3072
stop_after_epoch: 10
subdir: ${hydra:job.id}
train_split: 0.9
validation_video:
  enabled: true
  every_n_epochs: 1
  fps: 4.0
  sample_index: 0
  padding: 128
hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
trainer:
  accelerator: gpu
  devices: auto
  gradient_clip_val: 1.0
  max_epochs: 100
  precision: bf16-mixed
